### ISSUE TITLE
depth file giving wrong message (end of file) if not found

### ISSUE THREAD

**Issue by malej** [fengyanshi/FUNWAVE-TVD#14]
@fengyanshi we have found that if `depth.txt` is not found in the path, then the system gives a wrong/misleading message that `depth.txt end of file` as if it read it and it had incorrect size/dimensions.

- [ ] is this done click here if yes

**Comment by EmmaLofthouse** [comment]
This is also happening with the stations/gauges file

**Comment by fengyanshi** [comment]
@malej @EmmaLofthouse : I added check existing before reading depth in init.F and gauge files in io.F
