### ISSUE TITLE
bring all file input/output numbering to standard

### ISSUE THREAD

**Issue by malej** [fengyanshi/FUNWAVE-TVD#16]
Need to make sure you are using the same format/numbering for input and output of files (e.g., `eta_00001`, and change `vessel_0001` ==> `vessel_00001`)

**Comment by SUNXUEAO** [comment]
hi, how can I download FUNWAVE-TVD app from here, I can‘t find it .Thank  you ,

**Comment by fengyanshi** [comment]
download page:
https://fengyanshi.github.io/build/html/setup.html

**Comment by SUNXUEAO** [comment]
Can I import topographic map to FUNWAVE ？ Or I have to use the depth.txt ?
In the FUNWAVE-TVD3.3\simple_cases\tohoku_tsunami\postprocessing ,  Iwant know the tohoku_dem.JPG is a topographic map ？

**Comment by fengyanshi** [comment]
You cannot use a topographic map for FUNWAVE. The format for the bathymetry file can be found on the WIKI page: https://fengyanshi.github.io/build/html/grid.html
