### ISSUE TITLE
tsunami case does not run

### ISSUE THREAD

**Issue by stevenrbrandt** [fengyanshi/FUNWAVE-TVD#17]
The tsunami sample case does not run. The following (at least) are missing from the input.txt file:DX, DY, PLOT_INTV_STORM, OUT_STORM, and STORM_FILE.

**Comment by fengyanshi** [comment]
It is a case for spherical coordinate mode. You should modify Makefile. Remove -DCARTESIAN, -DSTORM. You don't need DX and DY, rather 
Lon_West = 132.0
Lat_South = -60.0
Dphi = 0.5
Dtheta = 0.5

**Comment by stevenrbrandt** [comment]
Of course. I forgot about that. Unfortunately, the code doesn't compile if I switch of -DCARTESIAN. mod_storm.F uses DX and DY instead of DX(i,j) and DY(i,j).

**Comment by fengyanshi** [comment]
did you switch off DSTORM?

**Comment by stevenrbrandt** [comment]
Didn't know I needed to. :)

**Comment by stevenrbrandt** [comment]
OK, with that change it runs. I have a few small modifications that can help users detect compilation errors like the ones I stumbled into. If you give me access, I can make it a pull request.

diff --git a/src/io.F b/src/io.F
index 7d7a99a..44d12da 100755
--- a/src/io.F
+++ b/src/io.F
@@ -231,6 +231,7 @@ SUBROUTINE READ_INPUT
       CALL READ_FLOAT(DX,FILE_NAME,'DX',ierr)
 
       IF(ierr==1)THEN
+         PRINT *,"Did you intend to use Spherical Coordinates?"
 # if defined (PARALLEL)
       if (myid.eq.0) THEN
          WRITE(*,'(A40,A40)')'DX:', 'NOT DEFINED, STOP'
diff --git a/src/mod_storm.F b/src/mod_storm.F
index 7f23076..86c8f34 100755
--- a/src/mod_storm.F
+++ b/src/mod_storm.F
@@ -290,6 +290,11 @@ SUBROUTINE STORM_FORCING
     ENDDO
     ENDDO
 
+#ifndef CARTESIAN
+#ifdef STORM
+#error "Please compile without -DSTORM when -DCARTESIAN is not set."
+#endif
+#endif
 
     DO J=Jbeg,Jend
     DO I=Ibeg,Iend

**Comment by malej** [comment]
You do not need admin access to create a pull request on Github. It is a best practice in Git to work from a forked repository and set Fengyan's original repo (FUNWAVE-TVD) as your upstream. Of course, you would have to clone from your fork rather than Fengyan's original repo. In addition, any code modifications should be preceded by a new branch, rather than working in the master and issuing a pull request to the admin directly into his master branch.

Matt

**Comment by stevenrbrandt** [comment]
OK, I forked and created a pull request.

**Comment by malej** [comment]
Merged. Thanks

**Comment by dikarojikin** [comment]
Hallo sir, how to modify tsunami parameters in funwave TVD?
