### ISSUE TITLE
Instability Check Failure

### ISSUE THREAD

**Issue by mayhl** [fengyanshi/FUNWAVE-TVD#32]
I ran into an issue where simulations because unstable but a failure state is not execute, i.e., a 99999 file is not thrown. I can tell the simulation has failed because the STATISTICS output in the LOG.txt file shows NaN for MassVolume and Energy. So a possible fixed would be to add checks for NaN when the STATISTICS are outputted.

**Comment by fengyanshi** [comment]
send me the case you are running

**Comment by malej** [comment]
fix added to statistics.F Thanks! closing
