### ISSUE TITLE
Cd matrix variables not recognized by the model

### ISSUE THREAD

**Issue by GabySalgado** [fengyanshi/FUNWAVE-TVD#35]
I noticed that FUNWAVE does not recognize the Cd matrix file when using the variables shown in the wiki (FRICTION_MATRIX & FRICTION_FILE). When I use those, the LOG file says to use instead Friction_Matrix & Cd_file. But when I do that, it still uses the Cd = 0.0 as default. There are no issues when using a fixed homogeneous Cd, but when I try to any Cd file, it  does not work.

**Comment by fengyanshi** [comment]
you are right, the names defined were not consistent with the wiki page. I changed to FRICTION_MATRIX & FRICTION_FILE and updated the github. please try the updated version and let me know if you get correct results.

**Comment by GabySalgado** [comment]
Awesome! So if I recompile Makefile-Onyx-intel it should be fine? I git pulled the fun wave repository and now that makefile is inside the old-version folder. Would you recommend me to use another makefile for Onyx instead?

**Comment by fengyanshi** [comment]
you can use the old makefile. Zhouteng is working on the documentation for the new makefiles.

**Comment by GabySalgado** [comment]
Ooooh cool. Thank you so much, Fengyan! I'll let you know how it goes.

**Comment by GabySalgado** [comment]
So far so good. Thanks for the help!
