### ISSUE TITLE
timer count not working in latest vesion

### ISSUE THREAD

**Issue by jreniel** [fengyanshi/FUNWAVE-TVD#4]
@fengyanshi ... we noticed that the timer `Simulation takes` is not working on the latest master branch version when outputting data in LOG.txt file ... for example

> ----------------- STATISTICS ----------------
>   TIME        DT
>   0.2501E+02  0.1325E-01
>   MassVolume  Energy      MaxEta      MinEta      Max U       Max V 
>   0.2663E+01  0.1526E+02  0.3060E+00  0.8320E-04  0.1907E+00  0.2044E+00
>   MaxTotalU   PhaseS      Froude 
>   0.2317E+00  0.1810E+01  0.1280E+00
>    PRINTING FILE NO.   251  TIME/TOTAL:       25.011 /      25.000
>  Simulation takes  0.000000000000000E+000 seconds
>  Normal Termination!

**Comment by fengyanshi** [comment]
@jreniel - it turns out the values tbegin and tend defined in main.F are not SAVEd. So I moved tbegin and tend into mod_global.F. Let me know if it works -thanks

**Comment by fengyanshi** [comment]
CALL WALL_TIME_SECS is not standard fortran, which caused the problem. I now used MPI standard: MPI_Wtime and Fortran 95 standard: CALL CPU_TIME. The updated file is main.F
