### ISSUE TITLE
Building with pgi

### ISSUE THREAD

**Issue by rafa-guedes** [fengyanshi/FUNWAVE-TVD#47]
Has someone successfully built funwave-tvd with pgi? I am trying to build the parallel version of the code and getting the error:

```
PGF90-S-0038-Symbol, rand, has not been explicitly declared (build/pre/io.f90)
```
I'm using version 19.4 of the compiler and the pgi flags defined in Make_Essential. The gnu version builds fine.

Thanks

**Comment by malej** [comment]
I remember a few years back leaving the PGI compiling issue alone, because it was a domino effect. After fixing one thing (like this Rand function) it was another and another. So, at the time we dropped it and simply went with GNU or Intel. Sorry
