### ISSUE TITLE
Cannot specify homogeneous friction field

### ISSUE THREAD

**Issue by rafa-guedes** [fengyanshi/FUNWAVE-TVD#48]
I was trying to run the model with an homogeneous friction field by specifying:

```
FRICTION_MATRIX = F
Cd_fixed = 0.002
```

but it looks like these are not being picked up by the model for some reason. I'm wondering if I'm missing something or if there could be some problem with the model version I'm building (Funwave 3.5).

The log file keeps telling me that:

```
 Cd DOES NOT EXIST. USE DEFAULT VALUE
Cd_fixed Default:  0.0, possibly you use
```

Changing the value of `Cd_fixed` results in no effects in my simulations.

The friction specification seems to be working as expected though when I define it with an inhomogeneous friction field by:

```
FRICTION_MATRIX = T
FRICTION_FILE = ./filename.txt
```

Thanks

**Comment by malej** [comment]
Can you try 

Cd = 0.002

Without  _fixed

**Comment by rafa-guedes** [comment]
That worked thanks!

It would be good to update the wiki if possible as Cd_fixed is the one mentioned there.
