### ISSUE TITLE
Adding Fortran standard compliant random number generator

### ISSUE THREAD

**Issue by floquet** [fengyanshi/FUNWAVE-TVD#9]
Want to provide an example of a standard compliant random number generator.

**Comment by malej** [comment]
@fengyanshi ... Dan Topa is going to add some features on his forked repository. Later on we can discuss these and see if we want to merge (via pull request as I was doing so far). He forked `FUNWAVE-TVD` into his account @floquet. I've encouraged his to get on our repo and start communicating. We will eventually setup Wiki on this repo (see above) and set Milestone tables and be able to assign tasks to team members.

**Comment by floquet** [comment]
[random_number_tester.tar.gz](https://github.com/fengyanshi/FUNWAVE-TVD/files/574236/random_number_tester.tar.gz)

Fortran standards-compliant module for random numbers. Includes make file and sample screen session. The file random_number_tester.f08 demonstrates basic features.

1. Allows for random number seeds to be stored which provides the capability to make full precision comparisons between code versions, compiler versions, and machine versions.

2. Allows for control of random number seeds across multiple processes.

3. Problem: when the difference between seeds is small, the differences between random numbers is small. Solution: swap byte order. For example, the wall time varies slowly. The byte flipped version of the time changes dramatically.

4. Unix systems offer a random number seed through dev/random. This package allows access to that feature.

5. Trapped errors like allocation failures feature a message which identifies the module and subroutine where the error occurred.

6. There is a routine which provides random integers \in [1, UpperBound].

compiler version: GCC version 7.0.0 20161030 (experimental)
compiler options: -fPIC -feliminate-unused-debug-symbols -mmacosx-version-min=10.12.1 -mtune=core2 -auxbase-strip random_number_tester.o -g -Og -Wall -Waliasing -Wconversion-extra -Wextra -Wsurprising -Wimplicit-procedure -Wintrinsics-std -Wuse-without-only -Wpedantic -fcheck=bounds -fmax-errors=5 -ffpe-trap=denormal -fbacktrace

**Comment by floquet** [comment]
[constants_tester.tar.gz](https://github.com/fengyanshi/FUNWAVE-TVD/files/574454/constants_tester.tar.gz)
(opens in a folder named alpha)

Fortran standards-compliant module for global constants. Includes make file and sample screen session. The file constants_tester.f08 demonstrates basic features.

1. How to USE module and identify constants needed in current scope.

2. Pi is automatically declared to full precision set (single, double, etc.).

3. Precision is controlled via the variable rp ('real precision').

4. A list module outputs the names of parameters and their settings.

5. Sample declaration of a complex number showing how complex precision is controlled.

6. Sample declaration of unit matrices showing how to use reshape.

7. Name binding allows gradual standardization of names (see R_earth).


compiler version: GCC version 7.0.0 20161030 (experimental)
compiler options: -fPIC -feliminate-unused-debug-symbols -mmacosx-version-min=10.12.1 -mtune=core2 -auxbase-strip constants_tester.o -g -Og -Wall -Waliasing -Wconversion-extra -Wextra -Wsurprising -Wimplicit-procedure -Wintrinsics-std -Wuse-without-only -Wpedantic -fcheck=bounds -fmax-errors=5 -ffpe-trap=denormal -fbacktrace

**Comment by floquet** [comment]
[harvest_command_line.tar.gz](https://github.com/fengyanshi/FUNWAVE-TVD/files/579283/harvest_command_line.tar.gz)
(opens in a folder name command_line_arguments)

Fortran standards-compliant module for reading arguments passed on the command line. This allows users to supply specifications at run time, an alternative to using a namelist.

In the following snippet, the execution command has three arguments which can used to specify paths, filenames, or data tags:

```
$ ./harvest_command_line mydata thesemodules title_for_run

The launch command was ./harvest_command_line mydata thesemodules title_for_run.
There are 3 arguments.
command line argument 1 is "mydata", length = 6
command line argument 2 is "thesemodules", length = 12
command line argument 3 is "title_for_run", length = 13

```
A prudent code will have default actions specified for the cases where no arguments are supplied.

**Comment by fengyanshi** [comment]
@malej I think it's a good idea to let Dan to do the work in his folk. thanks
